# Generated by Django 6.0.4 on 2026-04-17 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointment_email_sent_appointment_reminder_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='email_sent',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='sms_sent',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='whatsapp_sent',
        ),
    ]
