# Generated by Django 6.0.4 on 2026-04-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_problem_appointment_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.TextField(blank=True, null=True)),
                ('map_embed_url', models.URLField(help_text='Paste Google Maps embed URL')),
                ('image', models.ImageField(blank=True, null=True, upload_to='branches/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
