# Generated by Django 6.0.1 on 2026-04-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_registrationotp_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationotp',
            name='department',
        ),
    ]
