# Generated by Django 6.0.1 on 2026-04-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_registrationotp_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationotp',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='registrationotp',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
