# Generated by Django 6.0.1 on 2026-04-22 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_registrationotp_first_name_registrationotp_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationotp',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
