# Generated by Django 6.0.1 on 2026-04-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_registrationotp_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationotp',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
