# Generated by Django 6.0.1 on 2026-04-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_registrationotp_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrationotp',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='registrationotp',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='registrationotp',
            name='username',
        ),
        migrations.AlterField(
            model_name='registrationotp',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registrationotp',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='registrationotp',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='registrationotp',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor')], default='patient', max_length=20),
        ),
    ]
