# Generated by Django 6.0.1 on 2026-04-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_registrationotp_is_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationotp',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
